# Generated by Django 5.2 on 2025-04-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('agent_l1', '一级代理'), ('agent_l2', '二级代理')], default='agent_l1', max_length=10),
        ),
    ]
