# Generated by Django 5.2 on 2025-04-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_user_name_user_parent_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额'),
        ),
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='二级域名'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='是否是代理'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='月付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='quarterly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='季付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='template',
            field=models.CharField(blank=True, choices=[('web_1', '模板一'), ('web_2', '模板二'), ('web_3', '模板三'), ('web_4', '模板四')], max_length=10, null=True, verbose_name='网站模板'),
        ),
        migrations.AddField(
            model_name='user',
            name='traffic_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='流量价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='年付价格'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
