# Generated by Django 5.2 on 2025-04-07 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_balance_user_domain_user_is_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('type', models.CharField(choices=[('monthly', '月付'), ('quarterly', '季付'), ('yearly', '年付'), ('traffic', '流量')], max_length=20, verbose_name='套餐类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('traffic_total', models.BigIntegerField(verbose_name='总流量(字节)')),
                ('validity_days', models.IntegerField(verbose_name='有效期(天)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '套餐',
                'verbose_name_plural': '套餐',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='归属代理'),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', '管理员'), ('editor', '编辑'), ('agent_l1', '一级代理'), ('agent_l2', '二级代理'), ('customer', '客户')], default='editor', max_length=20),
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IP地址')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('device_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录记录',
                'verbose_name_plural': '登录记录',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='购买日期')),
                ('expire_date', models.DateTimeField(verbose_name='到期日期')),
                ('traffic_used', models.BigIntegerField(default=0, verbose_name='已使用流量(字节)')),
                ('traffic_total', models.BigIntegerField(verbose_name='总流量(字节)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL, verbose_name='客户')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='users.package', verbose_name='套餐')),
            ],
            options={
                'verbose_name': '客户套餐',
                'verbose_name_plural': '客户套餐',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='TrafficRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('traffic_used', models.BigIntegerField(default=0, verbose_name='使用流量(字节)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_records', to=settings.AUTH_USER_MODEL, verbose_name='客户')),
            ],
            options={
                'verbose_name': '流量记录',
                'verbose_name_plural': '流量记录',
                'ordering': ['-date'],
                'unique_together': {('customer', 'date')},
            },
        ),
    ]
