# Generated by Django 5.2 on 2025-04-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_package_user_agent_user_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='agent_backgrounds/', verbose_name='网站背景图'),
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='agent_logos/', verbose_name='网站Logo'),
        ),
        migrations.AddField(
            model_name='user',
            name='website_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='网站名称'),
        ),
    ]
