# Generated by Django 5.2 on 2025-04-08 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_background_user_logo_user_website_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='background',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website_name',
        ),
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='VPN服务', max_length=100, verbose_name='网站名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='website_templates/logos/', verbose_name='网站Logo')),
                ('background', models.ImageField(blank=True, null=True, upload_to='website_templates/backgrounds/', verbose_name='主页背景图')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_template', to=settings.AUTH_USER_MODEL, verbose_name='所属代理')),
            ],
            options={
                'verbose_name': '网站模板设置',
                'verbose_name_plural': '网站模板设置',
            },
        ),
    ]
