# Generated by Django 5.2 on 2025-04-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_background_remove_user_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='live_half_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='直播半年付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='live_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='直播月付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='live_quarterly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='直播季付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='live_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='直播年付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='normal_half_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='普通半年付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='normal_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='普通月付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='normal_quarterly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='普通季付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='normal_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='普通年付价格'),
        ),
    ]
