# Generated by Django 5.2 on 2025-04-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0003_agentpanel_country'),
        ('users', '0009_user_live_half_yearly_price_user_live_monthly_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='是否已验证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panels.agentpanel', verbose_name='所属代理'),
        ),
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='注册域名'),
        ),
    ]
