# Generated by Django 5.2 on 2025-04-20 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_verified_alter_user_agent_alter_user_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='易支付订单号')),
                ('out_trade_no', models.CharField(max_length=100, unique=True, verbose_name='商户订单号')),
                ('payment_type', models.CharField(choices=[('alipay', '支付宝'), ('wxpay', '微信支付'), ('qqpay', 'QQ钱包'), ('other', '其他')], default='other', max_length=20, verbose_name='支付方式')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='支付状态')),
                ('param', models.TextField(blank=True, null=True, verbose_name='业务扩展参数')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='节点国家')),
                ('node_count', models.IntegerField(default=1, verbose_name='节点数量')),
                ('node_protocol', models.CharField(blank=True, max_length=20, null=True, verbose_name='节点协议')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付订单',
                'verbose_name_plural': '支付订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
