# Generated by Django 5.2 on 2025-04-20 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_paymentorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('vmess', 'VMess'), ('vless', 'VLESS'), ('shadowsocks', 'Shadowsocks'), ('socks', 'Socks'), ('http', 'HTTP')], max_length=20, verbose_name='协议类型')),
                ('name', models.CharField(max_length=255, verbose_name='节点名称')),
                ('host', models.CharField(max_length=255, verbose_name='节点主机')),
                ('port', models.IntegerField(verbose_name='节点端口')),
                ('uuid', models.CharField(blank=True, max_length=40, null=True, verbose_name='UUID')),
                ('nodename', models.CharField(blank=True, max_length=40, null=True, verbose_name='nodename')),
                ('nodepassword', models.CharField(blank=True, max_length=40, null=True, verbose_name='nodepassword')),
                ('panel_id', models.IntegerField(blank=True, null=True, verbose_name='面板ID')),
                ('panel_node_id', models.IntegerField(blank=True, null=True, verbose_name='面板节点ID')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('expired', '已过期'), ('deleted', '已删除')], default='active', max_length=20, verbose_name='节点状态')),
                ('expiry_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('config_text', models.TextField(blank=True, null=True, verbose_name='配置文本')),
                ('qrcode_data', models.TextField(blank=True, null=True, verbose_name='二维码数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='users.paymentorder', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '节点信息',
                'verbose_name_plural': '节点信息',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_nodei_user_id_90e40c_idx'), models.Index(fields=['order'], name='users_nodei_order_i_8f288a_idx'), models.Index(fields=['protocol'], name='users_nodei_protoco_fbf433_idx')],
            },
        ),
    ]
