# Generated by Django 5.2 on 2025-04-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_nodeinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodeinfo',
            old_name='nodepassword',
            new_name='node_password',
        ),
        migrations.RenameField(
            model_name='nodeinfo',
            old_name='nodename',
            new_name='node_user',
        ),
        migrations.AddField(
            model_name='nodeinfo',
            name='remark',
            field=models.CharField(max_length=255, null=True, verbose_name='节点备注'),
        ),
        migrations.AlterField(
            model_name='nodeinfo',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('expired', '已过期'), ('deleted', '已删除'), ('pending', '待处理')], default='active', max_length=20, verbose_name='节点状态'),
        ),
    ]
