# Generated by Django 5.2 on 2025-04-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_nodepassword_nodeinfo_node_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quarterly_price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='traffic_price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yearly_price',
        ),
        migrations.AddField(
            model_name='user',
            name='custom_live_half_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自定义直播半年付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_live_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自定义直播月付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_live_quarterly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自定义直播季付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_live_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自定义直播年付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_normal_half_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自定义普通半年付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_normal_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自定义普通月付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_normal_quarterly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自定义普通季付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_normal_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自定义普通年付价格'),
        ),
    ]
