# Generated by Django 5.2 on 2025-04-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_monthly_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='nodeinfo',
            name='host_config',
            field=models.CharField(default='{}', max_length=255, verbose_name='节点信息'),
        ),
        migrations.AddField(
            model_name='nodeinfo',
            name='remark_custom',
            field=models.CharField(max_length=255, null=True, verbose_name='节点自定义备注'),
        ),
    ]
