# Generated by Django 5.2 on 2025-04-26 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_nodeinfo_name_nodeinfo_host_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='udp',
            field=models.BooleanField(default=False, verbose_name='是否支持UDP'),
        ),
        migrations.AddField(
            model_name='nodeinfo',
            name='udp_config',
            field=models.TextField(blank=True, null=True, verbose_name='UDP配置信息'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_type',
            field=models.CharField(choices=[('alipay', '支付宝'), ('wxpay', '微信支付'), ('other', '其他')], default='other', max_length=20, verbose_name='支付方式'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100, unique=True, verbose_name='发票编号')),
                ('title', models.CharField(max_length=255, verbose_name='发票抬头')),
                ('tax_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='税号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='开票金额')),
                ('content', models.CharField(default='技术服务费', max_length=255, verbose_name='发票内容')),
                ('status', models.CharField(choices=[('pending', '待开具'), ('issued', '已开具'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='发票状态')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='接收邮箱')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='开具时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.paymentorder', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_invoi_user_id_47ff79_idx'), models.Index(fields=['order'], name='users_invoi_order_i_bc5365_idx'), models.Index(fields=['invoice_no'], name='users_invoi_invoice_a8d42f_idx')],
            },
        ),
    ]
