# Generated by Django 5.2 on 2025-04-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0002_alter_transitaccount_token'),
        ('users', '0016_nodeinfo_udp_nodeinfo_udp_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_transit_half_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自定义中转半年付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_transit_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自定义中转月付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_transit_quarterly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自定义中转季付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_transit_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自定义中转年付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_transit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transits.transitaccount', verbose_name='默认中转账号'),
        ),
        migrations.AddField(
            model_name='user',
            name='transit_half_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='中转半年付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='transit_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='中转月付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='transit_quarterly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='中转季付价格'),
        ),
        migrations.AddField(
            model_name='user',
            name='transit_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='中转年付价格'),
        ),
    ]
