# Generated by Django 5.2 on 2025-05-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='qq_qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/qq/', verbose_name='QQ二维码'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='wechat_qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/wechat/', verbose_name='微信二维码'),
        ),
    ]
