# Generated by Django 5.2 on 2025-05-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_contactinfo_qq_qrcode_contactinfo_wechat_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='udp_host',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UDP中转主机'),
        ),
    ]
