# Generated by Django 5.2 on 2025-05-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_nodeinfo_udp_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='最后登录IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='最后登录IP'),
        ),
    ]
