# Generated by Django 5.2 on 2025-04-09 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, verbose_name='IP地址')),
                ('port', models.CharField(max_length=10, verbose_name='端口')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('panel_type', models.CharField(choices=[('x-ui', 'x-ui'), ('3x-ui', '3x-ui')], max_length=10, verbose_name='面板类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在线')),
                ('last_restart', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后重启时间')),
                ('cpu_usage', models.FloatField(default=0, verbose_name='CPU使用率')),
                ('memory_usage', models.FloatField(default=0, verbose_name='内存使用率')),
                ('disk_usage', models.FloatField(default=0, verbose_name='硬盘使用率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代理面板',
                'verbose_name_plural': '代理面板',
                'ordering': ['-created_at'],
            },
        ),
    ]
