# Generated by Django 5.2 on 2025-04-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpanel',
            name='cookie',
            field=models.TextField(blank=True, null=True, verbose_name='登录Cookie'),
        ),
        migrations.AlterField(
            model_name='agentpanel',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True, verbose_name='CPU使用率'),
        ),
        migrations.AlterField(
            model_name='agentpanel',
            name='disk_usage',
            field=models.FloatField(blank=True, null=True, verbose_name='磁盘使用率'),
        ),
        migrations.AlterField(
            model_name='agentpanel',
            name='ip_address',
            field=models.CharField(max_length=255, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='agentpanel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='agentpanel',
            name='last_restart',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后重启时间'),
        ),
        migrations.AlterField(
            model_name='agentpanel',
            name='memory_usage',
            field=models.FloatField(blank=True, null=True, verbose_name='内存使用率'),
        ),
        migrations.AlterField(
            model_name='agentpanel',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='agentpanel',
            name='port',
            field=models.IntegerField(verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='agentpanel',
            name='username',
            field=models.CharField(max_length=255, verbose_name='用户名'),
        ),
    ]
