# Generated by Django 5.2 on 2025-04-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_agentpanel_cookie_alter_agentpanel_cpu_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpanel',
            name='country',
            field=models.CharField(default='未知', max_length=100, verbose_name='国家'),
        ),
    ]
