# Generated by Django 5.2 on 2025-04-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0003_agentpanel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpanel',
            name='nodes_count',
            field=models.IntegerField(default=0, verbose_name='节点数量'),
        ),
    ]
