# Generated by Django 5.2 on 2025-04-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0004_agentpanel_nodes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpanel',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
    ]
