# Generated by Django 5.2 on 2025-04-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0005_agentpanel_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpanel',
            name='used_ports',
            field=models.TextField(blank=True, default='', verbose_name='已使用的端口'),
        ),
    ]
