# Generated by Django 5.2 on 2025-04-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0006_agentpanel_used_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpanel',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='纯IP地址'),
        ),
    ]
