# Generated by Django 5.2 on 2025-04-06 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CDK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='优惠码')),
                ('discount', models.IntegerField(verbose_name='折扣百分比')),
                ('max_uses', models.IntegerField(verbose_name='最大使用次数')),
                ('used_count', models.IntegerField(default=0, verbose_name='已使用次数')),
                ('valid_from', models.DateTimeField(verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'CDK优惠码',
                'verbose_name_plural': 'CDK优惠码',
                'ordering': ['-created_at'],
            },
        ),
    ]
