# Generated by Django 5.2 on 2025-06-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='content_type',
            field=models.CharField(choices=[('text', '文本消息'), ('image', '图片消息')], default='text', max_length=10, verbose_name='内容类型'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='聊天图片'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='消息内容'),
        ),
    ]
