# Generated by Django 5.2 on 2025-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransitAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('token', models.CharField(default=None, max_length=100, verbose_name='token')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
                ('traffic', models.TextField(default='{"used": 0, "total": 0}', verbose_name='流量')),
                ('rules', models.TextField(default='{"used": 0, "max": 10}', verbose_name='规则数')),
                ('default_inbound', models.TextField(default='{}', verbose_name='默认入口')),
                ('default_outbound', models.TextField(default='{}', verbose_name='默认出口')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('deleted', '已删除')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '中转账号',
                'verbose_name_plural': '中转账号',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username'], name='transits_tr_usernam_7aeee4_idx'), models.Index(fields=['status'], name='transits_tr_status_86d3c9_idx')],
            },
        ),
    ]
