# Generated by Django 5.2 on 2025-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitaccount',
            name='token',
            field=models.CharField(default='', max_length=100, verbose_name='token'),
        ),
    ]
