# Generated by Django 5.2 on 2025-06-28 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0002_alter_transitaccount_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('domain', models.CharField(max_length=255, verbose_name='域名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='代理')),
            ],
            options={
                'verbose_name': '中转域名',
                'verbose_name_plural': '中转域名',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent'], name='transits_tr_agent_i_bba53c_idx'), models.Index(fields=['ip'], name='transits_tr_ip_027664_idx'), models.Index(fields=['domain'], name='transits_tr_domain_a4d4cc_idx')],
                'unique_together': {('agent', 'name')},
            },
        ),
    ]
