# Generated by Django 5.2 on 2025-08-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0003_transitdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitdomain',
            name='ip',
            field=models.CharField(max_length=255, verbose_name='IP地址或域名'),
        ),
    ]
